#!/usr/bin/env bash
# safe_agent.sh — simulates a well-behaved coding agent
#
# Only writes to src/ — inside the strict policy pack's allow_write patterns.
# Airlock governance: all writes allowed, all events recorded, run exits 0.
#
# Use in Airlock:
#   ./airlock run --agent generic-shell \
#     --cmd "$(cat samples/scripts/safe_agent.sh)" \
#     --repo . --policy-pack strict --approval deny-high-risk

set -euo pipefail

mkdir -p src

echo "# Generated by safe_agent.sh" > src/artifact.txt
echo "Build timestamp: $(date -u)" >> src/artifact.txt
echo "Status: success" >> src/artifact.txt

echo "Tests: PASS" > src/test_results.txt

echo "Safe agent run complete. Files written: src/artifact.txt, src/test_results.txt"
