#!/usr/bin/env bash
# Sentinel Airlock — Operator-mode end-to-end demo (browser-driven)
#
# This is the fullest operator walkthrough: it builds a fresh target repo with a
# real allow/deny policy, runs a governed agent that makes BOTH allowed writes
# (src/, docs/, slides/drafts/) and denied writes (.env, secrets/, prod/,
# slides/final/), then hands you a background operator viewer so you can perform
# the rollback from the browser and watch the page change to "Workspace rolled
# back".
#
# Like demo-ui-rollback.sh, this script does NOT run rollback for you — the whole
# point is to prove the *browser* click path. It only sets the stage and verifies
# the result after you click.
#
# What "rollback" means here:
#   Airlock restores .airlock/workspaces/<run_id>/repo — the isolated execution
#   sandbox. Your ORIGINAL target repo is NEVER modified. Workspace-only.
#
# Prerequisites: Go 1.22+, make, python3. No Docker, no network, no API keys.
#
# Override the viewer port with: PORT=8090 bash samples/operator-walkthrough.sh
set -euo pipefail

ROOT="$(cd "$(dirname "$0")/.." && pwd)"
cd "$ROOT"

PORT="${PORT:-8080}"
BASE_URL="http://127.0.0.1:${PORT}"
DEMO_REPO="/tmp/airlock-operator-demo"

echo "==========================================================="
echo " Sentinel Airlock — Operator-mode End-to-End Demo"
echo "==========================================================="
echo ""

# ── 1. Build ──────────────────────────────────────────────────
echo "[ 1/7 ] Building binary..."
make build --quiet
echo "        Binary: $(./airlock --version)"
echo ""

# ── 2. Stop any existing viewer ───────────────────────────────
echo "[ 2/7 ] Stopping any existing viewer..."
./airlock serve --stop >/dev/null 2>&1 || true
echo ""

# ── 3. Prepare a fresh target repo with a real allow/deny policy ─
echo "[ 3/7 ] Preparing demo target repo at $DEMO_REPO ..."
rm -rf "$DEMO_REPO"
mkdir -p "$DEMO_REPO/src" "$DEMO_REPO/docs" \
         "$DEMO_REPO/slides/final" "$DEMO_REPO/slides/drafts" \
         "$DEMO_REPO/secrets" "$DEMO_REPO/prod"

cat > "$DEMO_REPO/README.md" <<'EOF'
# Airlock Operator Demo

This is a small target project for testing governed agent execution.
EOF

cat > "$DEMO_REPO/src/app.py" <<'EOF'
def hello():
    return "hello from original app"

if __name__ == "__main__":
    print(hello())
EOF

cat > "$DEMO_REPO/slides/final/final.md" <<'EOF'
# Final deck

Do not modify this file.
EOF

cat > "$DEMO_REPO/prod/deploy.yaml" <<'EOF'
environment: production
locked: true
EOF

cat > "$DEMO_REPO/.env" <<'EOF'
SECRET_KEY=do-not-touch
EOF

cat > "$DEMO_REPO/airlock.yaml" <<'EOF'
policy:
  deny_write:
    - ".env"
    - "**/.env"
    - "secrets/**"
    - "prod/**"
    - "slides/final/**"
  allow_write:
    - "src/**"
    - "docs/**"
    - "slides/drafts/**"
    - "README.md"

network:
  mode: "off"
EOF

echo "        Files:"
find "$DEMO_REPO" -maxdepth 3 -type f | sort | sed 's/^/          /'
echo ""

# ── 4. Start the operator viewer in the background ────────────
echo "[ 4/7 ] Starting operator viewer in the background (port $PORT)..."
./airlock serve --background --port "$PORT" >/dev/null 2>&1 || true
sleep 1
./airlock serve --status
echo ""

# ── 5. Run a governed agent (allowed + denied writes) ─────────
echo "[ 5/7 ] Running a governed agent (allowed + denied writes)..."
RUN_LOG="/tmp/airlock-operator-run.log"
./airlock run \
  --repo "$DEMO_REPO" \
  --agent generic-shell \
  --sandbox workspace \
  --policy "$DEMO_REPO/airlock.yaml" \
  --policy-pack strict \
  --cmd "bash -lc '
    set +e

    echo \"[agent] reading project\"
    cat README.md >/dev/null

    echo \"[agent] allowed source edit\"
    cat >> src/app.py <<PYEOF

def generated_feature():
    return \"generated safely inside Airlock workspace\"
PYEOF

    echo \"[agent] allowed docs write\"
    mkdir -p docs
    cat > docs/agent-notes.md <<MDEOF
# Agent Notes

The agent analyzed the project and added a generated feature.

- allowed: src/app.py
- allowed: docs/agent-notes.md
- attempted protected writes below
MDEOF

    echo \"[agent] allowed draft slide\"
    mkdir -p slides/drafts
    echo \"# Draft generated by agent\" > slides/drafts/agent-draft.md

    echo \"[agent] run python check\"
    python3 src/app.py

    echo \"[agent] attempt protected env write\"
    echo \"SECRET_KEY=hacked\" > .env

    echo \"[agent] attempt protected secret write\"
    echo \"private-key\" > secrets/demo.pem

    echo \"[agent] attempt protected final slide write\"
    echo \"bad final change\" >> slides/final/final.md

    echo \"[agent] attempt protected prod change\"
    echo \"locked: false\" > prod/deploy.yaml

    echo \"[agent] done\"
  '" > "$RUN_LOG" 2>&1 || true

# Prefer the printed "Run ID:" line; fall back to newest run dir.
RUN_ID="$(awk '/^Run ID:/ {print $3}' "$RUN_LOG" | tail -1)"
if [ -z "${RUN_ID:-}" ]; then
  RUN_ID="$(ls -1t .airlock/runs 2>/dev/null | head -n 1 || true)"
fi
if [ -z "${RUN_ID:-}" ]; then
  echo "ERROR: could not determine run id. See $RUN_LOG"
  ./airlock serve --stop >/dev/null 2>&1 || true
  exit 1
fi

RUN_URL="${BASE_URL}/runs/${RUN_ID}"
echo "        Run ID:  $RUN_ID"
echo "        Run URL: $RUN_URL"
echo ""

# ── 6. Open the run and describe the before/after states ──────
echo "[ 6/7 ] Opening the run page in your browser..."
if command -v open >/dev/null 2>&1; then open "$RUN_URL" >/dev/null 2>&1 || true
elif command -v xdg-open >/dev/null 2>&1; then xdg-open "$RUN_URL" >/dev/null 2>&1 || true; fi
echo ""
echo "  BEFORE CLICK — the run page should show:"
echo "    - Header:            operator viewer / local operator mode"
echo "    - Workspace Mutation with allowed changes: src/app.py, docs/agent-notes.md,"
echo "                         slides/drafts/agent-draft.md"
echo "    - Denied/reverted writes: .env, secrets/demo.pem, prod/deploy.yaml,"
echo "                         slides/final/final.md"
echo "    - Governance badge:  rollback: available  (+ 'rollback available')"
echo "    - Rollback section:  'Rollback available — restore workspace from cp-0'"
echo "    - A button:          'Restore workspace'"
echo "    - Replay summary:    rollback events = 0"
echo "    - Environment guardrail collapsed"
echo ""
echo "  CLI cross-check before rollback:"
./airlock inspect "$RUN_ID" || true
./airlock verify "$RUN_ID" || true
echo ""
echo "  ACTION:"
echo "    Click 'Restore workspace', accept the confirmation dialog. The button"
echo "    shows 'Restoring…' and the page returns with a green"
echo "    'Rollback complete — workspace restored from cp-0.' banner."
echo ""
echo "  AFTER CLICK — the page should now show:"
echo "    - Top card:          '↩ Workspace rolled back'"
echo "    - Governance badge:  rollback: complete  +  rolled back (full)"
echo "    - Replay summary:    rollback events = 1"
echo "    - review:            needs-attention"
echo "    - verify:            verified-unsigned (clean)"
echo ""

# ── 7. Wait for the operator to click, then verify + stop ─────
echo "[ 7/7 ] Perform the click in the browser, then press Enter to verify..."
read -r _ || true
echo ""
echo "        Verifying run $RUN_ID from artifacts:"
if [ -f ".airlock/runs/$RUN_ID/rollback.json" ]; then
  echo "        rollback.json     present ✓"
else
  echo "        rollback.json     NOT found — did you click 'Restore workspace'?"
fi
if grep -q 'ROLLBACK' ".airlock/runs/$RUN_ID/events.jsonl" 2>/dev/null; then
  echo "        ROLLBACK event    recorded ✓"
fi
if grep -q 'needs-attention' ".airlock/runs/$RUN_ID/review.json" 2>/dev/null; then
  echo "        review            needs-attention ✓"
fi
./airlock inspect "$RUN_ID" || true
./airlock verify "$RUN_ID" || true
echo ""

echo "        Honesty check — the ORIGINAL repo must be untouched by rollback:"
echo "        --- $DEMO_REPO/src/app.py (tail) ---"
tail -n 8 "$DEMO_REPO/src/app.py" | sed 's/^/          /'
echo "        --- protected files (unchanged) ---"
sed 's/^/          /' "$DEMO_REPO/.env"
sed 's/^/          /' "$DEMO_REPO/slides/final/final.md"
sed 's/^/          /' "$DEMO_REPO/prod/deploy.yaml"
echo ""

echo "        Stopping the viewer..."
./airlock serve --stop || true
echo ""
echo "==========================================================="
echo " Operator-mode demo complete."
echo ""
echo " This demo proved the browser click path — the script itself"
echo " never ran rollback. Read-only mode (serve --read-only) would"
echo " show 'Rollback instructions' with no mutating button instead."
echo "==========================================================="
