#!/usr/bin/env python3
"""
Sentinel Airlock — BYOM Agent Runtime Integration

A process-based agent that reads project context, produces structured output,
and optionally demonstrates Airlock governance by attempting policy-denied writes.

Default mode: Python standard library only. No network. No API keys required.

Optional hooks for LLM-backed agents are documented in README.md:
  - Ollama (local inference)
  - llama.cpp server (OpenAI-compatible)
  - vLLM / any OpenAI-compatible endpoint
  - LangChain / LangGraph

Run through Airlock:
  ./airlock run \\
    --agent generic-shell \\
    --cmd "python3 /path/to/agent.py --task 'Summarize project' --context README.md" \\
    --repo /path/to/project \\
    --policy /path/to/policy.airlock.yaml
"""

import argparse
import json
import os
import sys
from datetime import datetime, timezone
from pathlib import Path


def log(msg: str) -> None:
    """Structured log to stdout — Airlock captures this as AGENT_STDOUT events."""
    print(f"[byom-agent] {msg}", flush=True)


def read_context(context_path: str) -> str:
    p = Path(context_path)
    if not p.exists():
        log(f"WARN: context file not found: {context_path}")
        return f"(context file not found: {context_path})"
    content = p.read_text(encoding="utf-8")
    log(f"read context: {len(content.splitlines())} lines, {len(content.split())} words from {context_path}")
    return content


def analyze_context(context: str, task: str) -> dict:
    """
    Produce a structured analysis from context + task using deterministic rules.

    In a BYOM integration backed by a local model, replace this function with
    a call to Ollama, llama.cpp, vLLM, or any OpenAI-compatible endpoint.
    See README.md for connection patterns.
    """
    lines = context.splitlines()
    word_count = len(context.split())
    headings = [l.strip() for l in lines if l.startswith("#")]
    code_blocks = context.count("```")
    bullet_lines = [l for l in lines if l.strip().startswith(("- ", "* ", "+ "))]

    summary_lines = []
    for line in lines[:30]:
        stripped = line.strip()
        if stripped and not stripped.startswith("#") and len(stripped) > 20:
            summary_lines.append(stripped)
        if len(summary_lines) >= 3:
            break

    return {
        "task": task,
        "context_lines": len(lines),
        "context_words": word_count,
        "context_code_blocks": code_blocks // 2,
        "headings": headings[:12],
        "bullet_count": len(bullet_lines),
        "summary": " ".join(summary_lines[:2]) or "(no prose content detected)",
        "backend": "stdlib-deterministic",
    }


def write_notes(output_path: str, task: str, analysis: dict, attempt_risky: bool) -> None:
    p = Path(output_path)
    p.parent.mkdir(parents=True, exist_ok=True)
    ts = datetime.now(timezone.utc).strftime("%Y-%m-%dT%H:%M:%SZ")

    lines = [
        "# BYOM Agent Notes",
        "",
        f"> Generated by Sentinel Airlock BYOM Agent Runtime Integration",
        f"> Timestamp: {ts}",
        f"> Backend: {analysis['backend']}",
        "",
        "## Task",
        "",
        f"{task}",
        "",
        "## Context Analysis",
        "",
        f"| Metric | Value |",
        f"|---|---|",
        f"| Lines | {analysis['context_lines']} |",
        f"| Words | {analysis['context_words']} |",
        f"| Sections | {len(analysis['headings'])} |",
        f"| Code blocks | {analysis['context_code_blocks']} |",
        f"| Bullet points | {analysis['bullet_count']} |",
        "",
        "## Sections Detected",
        "",
    ]

    for h in analysis["headings"]:
        lines.append(f"- `{h}`")
    if not analysis["headings"]:
        lines.append("- (none detected)")

    lines += [
        "",
        "## Content Summary",
        "",
        analysis["summary"],
        "",
        "## Governance Audit Trail",
        "",
        "This file was produced by the BYOM agent running under Airlock governance.",
        "All file writes were recorded in `events.jsonl` and are verifiable:",
        "",
        "```bash",
        "# Verify artifact integrity",
        "airlock verify <run_id>",
        "",
        "# Replay governed event timeline",
        "airlock replay <run_id> --tail 20",
        "",
        "# Open evidence report",
        "open .airlock/runs/<run_id>/report/index.html",
        "```",
        "",
    ]

    if attempt_risky:
        lines += [
            "## Governance Test: Policy-Denied Write Attempts",
            "",
            "This run was launched with `--attempt-risky`. The agent attempted writes to:",
            "- `.env` — governed: should be blocked by `deny_write: [\"**/.env\"]`",
            "- `secrets/demo.pem` — governed: should be blocked by `deny_write: [\"secrets/**\"]`",
            "",
            "Expected Airlock behavior: POLICY_DENY events in `events.jsonl`, files reverted.",
            "Check `airlock replay <run_id>` for `⛔` markers on the denied events.",
            "",
        ]

    p.write_text("\n".join(lines) + "\n", encoding="utf-8")
    log(f"wrote output: {output_path} ({p.stat().st_size} bytes)")


def attempt_risky_writes() -> None:
    """
    Attempt writes to policy-denied paths. Airlock blocks and reverts these;
    POLICY_DENY events are recorded in events.jsonl with diffs.

    This is intentional: it demonstrates the governance boundary working correctly.
    The run exits 0 (agent completes); the writes are denied by Airlock, not the agent.
    """
    targets = [
        (".env",             "# Risky write: BYOM governance test\nSECRET_KEY=byom-risky-demo\nDB_PASS=not-a-real-secret\n"),
        ("secrets/demo.pem", "-----BEGIN CERTIFICATE-----\nBYOM_DEMO_NOT_REAL_DO_NOT_USE\n-----END CERTIFICATE-----\n"),
    ]
    for rel_path, content in targets:
        p = Path(rel_path)
        try:
            p.parent.mkdir(parents=True, exist_ok=True)
            p.write_text(content, encoding="utf-8")
            log(f"wrote risky file (Airlock should revert this): {rel_path}")
        except OSError as e:
            log(f"risky write blocked at OS level: {rel_path}: {e}")


def main() -> int:
    parser = argparse.ArgumentParser(
        prog="byom-agent",
        description=(
            "BYOM Agent Runtime Integration for Sentinel Airlock. "
            "Reads project context, produces structured notes, optionally tests governance."
        ),
        formatter_class=argparse.RawDescriptionHelpFormatter,
        epilog="""
examples:
  # Normal governed run
  python3 agent.py --task "Summarize project" --context README.md

  # With risky write test (demonstrates Airlock policy denial)
  python3 agent.py --task "Audit project" --context README.md --attempt-risky

  # Custom output path
  python3 agent.py --task "Document API" --context src/api.md --output docs/api-notes.md

optional model backends (see README.md for integration patterns):
  Ollama:             pip install ollama
  OpenAI-compatible:  pip install openai  (works with vLLM, llama.cpp, Ollama)
  LangChain:          pip install langchain-core langchain-ollama
        """,
    )
    parser.add_argument(
        "--task",
        default="Summarize project context and produce structured notes",
        help="Task description passed to the agent",
    )
    parser.add_argument(
        "--context",
        default="README.md",
        help="Project context file to read (relative to workspace CWD)",
    )
    parser.add_argument(
        "--output",
        default="docs/byom-agent-notes.md",
        help="Output file path (relative to workspace CWD); parent dirs are created",
    )
    parser.add_argument(
        "--attempt-risky",
        action="store_true",
        help=(
            "Also attempt writes to policy-denied paths (.env, secrets/demo.pem) "
            "to demonstrate Airlock governance in action"
        ),
    )
    args = parser.parse_args()

    log("=" * 60)
    log(f"BYOM Agent Runtime Integration — Sentinel Airlock")
    log(f"task:    {args.task!r}")
    log(f"context: {args.context}")
    log(f"output:  {args.output}")
    log(f"risky:   {args.attempt_risky}")
    log("=" * 60)

    # Step 1: Read project context
    log("step 1/3: reading project context")
    context = read_context(args.context)

    # Step 2: Analyze context and plan output
    log("step 2/3: analyzing context")
    analysis = analyze_context(context, args.task)
    log(
        f"analysis: sections={len(analysis['headings'])} "
        f"words={analysis['context_words']} "
        f"bullets={analysis['bullet_count']}"
    )

    # Step 3: Write output
    log("step 3/3: writing output")
    write_notes(args.output, args.task, analysis, args.attempt_risky)

    # Optional: governance test — attempt writes Airlock should deny
    if args.attempt_risky:
        log("governance test: attempting policy-denied writes")
        log("  Airlock should block and revert these; check events.jsonl for POLICY_DENY")
        attempt_risky_writes()
        log("governance test complete")

    log("=" * 60)
    log("done — all steps complete")
    log(f"output written to: {args.output}")
    if args.attempt_risky:
        log("policy-denied writes attempted — verify with: airlock replay <run_id> --tail 20")
    log("=" * 60)
    return 0


if __name__ == "__main__":
    sys.exit(main())
